name: "\U0001F41B Bug report"
description: Report an issue of QWER
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!  **Before you start, make sure you have the latest versions of QWER.**
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is and/or expected behavior is.
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: A link to a repository that reproduces the issue if appropriate. And, list steps to reproduce the behavior.
      placeholder: Reproduction
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: 'Please include browser console and server logs around the time this bug occurred. Please try not to insert an image but copy paste the log text.'
      render: shell
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite,@kwchang0831}"`
      render: shell
      placeholder: System, Binaries, Browsers
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
